schema: ./schema.graphql # ./introspection.json #https://graphql.anilist.co #
documents: './src/**/*.{ts,tsx,svelte}'
extensions:
  codegen:
    emitLegacyCommonJSImports: false

    config:
      skipDocumentsValidation: true
      useTypeImports: true
      immutableTypes: true
      # namingConvention: keep
      # omitOperationSuffix: true

    generates:
      src/gql/:
        preset: ./preset.cjs
        presetConfig:
          unmaskFunctionName: useFragment
          fragmentMasking: true
        plugins:
          - fragments.cjs:
          - typescript-urql-graphcache:

      ./src/gql/urql-introspection.ts:
        plugins:
          - urql-introspection

      # ./schema.graphql:
      #   plugins:
      #     - schema-ast

      # ./introspection.json:
      #   plugins:
      #     - introspection
      # config:
      #   minify: true
